# Test on Windows Desktop using Helix
parameters:
- name: helixQueueName
  type: string
- name: testRunName
  type: string
  default: ''
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: testArguments
  type: string
  default: ''
- name: helixApiAccessToken
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  pool:
    # Note that when helix is enabled, the agent running this job is essentially
    # a thin client that kicks off a helix job and waits for it to complete.
    # We can use any windows VM, currently we use a the NetCore queues to take advantage of the high machine parallelism
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals 1es-windows-2022     
    ${{ else }}:
      name: NetCore-Public
      demands: ImageOverride -equals 1es-windows-2022-open
  timeoutInMinutes: 120
  steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: Download Test Payload
      inputs:
        artifact: ${{ parameters.testArtifactName }}
        path: '$(Build.SourcesDirectory)'

    - task: BatchScript@1
      displayName: Rehydrate RunTests
      inputs:
        filename: ./artifacts/bin/RunTests/${{ parameters.configuration }}/net7.0/rehydrate.cmd
      env:
        HELIX_CORRELATION_PAYLOAD: '$(Build.SourcesDirectory)\.duplicate'

    - task: PowerShell@2
      displayName: Run Unit Tests
      inputs:
        filePath: eng/build.ps1
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          arguments: -ci -helix -configuration ${{ parameters.configuration }} -helixQueueName ${{ parameters.helixQueueName }} -helixApiAccessToken ${{ parameters.helixApiAccessToken }} ${{ parameters.testArguments }} -collectDumps        
        ${{ else }}:
          arguments: -ci -helix -configuration ${{ parameters.configuration }} -helixQueueName ${{ parameters.helixQueueName }} ${{ parameters.testArguments }} -collectDumps
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}
