# See https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md

name: Inter-branch merge
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      configuration_file_branch:
        description: 'Branch to use for configuration file'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: 'eng/config/branch-merge.jsonc'
      configuration_file_branch: ${{ inputs.configuration_file_branch || 'main' }}
  # The config does not support multiple flows from the same source branch, so we need to run twice:
  merge-2:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: 'eng/config/branch-merge-2.jsonc'
      configuration_file_branch: ${{ inputs.configuration_file_branch || 'main' }}
